name: Use Alternative Files
description: Uses Alternative Files
branding:
  icon: file
  color: blue
inputs:
  target:
    description: Target file or directory
    required: true
    default: .
  keyword:
    description: Keyword to designate alternative files
    required: true
    default: alt
runs:
  using: composite
  steps:
  
    - shell: bash
      env:
        TARGET: ${{ inputs.target }}
        KEYWORD: ${{ inputs.keyword }}
      run: |
        use_alternative_files () {
          if [[ -d "$1" ]]; then
            local items=$(ls -A1 "$1" | jq -Rs 'split("\n")[:-1]')
            if [[ $(echo "$items" | jq length) > 0 ]]; then
              for (( i=0; i<$(echo "$items" | jq length); i++ )); do
                use_alternative_files "$1/$(echo "$items" | jq -r --argjson i $i '.[$i]')"
              done
            fi
          elif [[ -f "$1" ]]; then
            local basename=$(basename "$1")
            local alt_file="$(dirname "$1")/${basename%.*}.$KEYWORD.${basename##*.}"
            if [[ -f "$alt_file" ]]; then
              mv -f "$alt_file" "$1"
            fi
          fi
        }

        use_alternative_files "$TARGET"
