name: Use Alternative Files
description: Uses Alternative Files
branding:
  icon: file
  color: blue
inputs:
  target:
    description: Target file or directory
    required: true
    default: .
  keyword:
    description: Keyword to designate alternative files
    required: true
    default: alt
runs:
  using: composite
  steps:
  
    - shell: bash
      env:
        TARGET: ${{ inputs.target }}
        KEYWORD: ${{ inputs.keyword }}
      run: |
        use_alternative_files () {
          if [[ -d "$1" ]]; then
            for item in "$1"/* "$1"/.[!.]* "$1"/..?*; do
              case $item in
                "$1/*"|"$1/.[!.]*"|"$1/..?*") 
                  ;; # skip
                *) 
                  use_alternative_files "$item"
                  ;;
              esac
            done
          elif [[ -f "$1" ]]; then
            local basename=$(basename "$1")
            local alt_file="$(dirname "$1")/${basename%.*}.$KEYWORD.${basename##*.}"
            if [[ -f "$alt_file" ]]; then
              mv -f "$alt_file" "$1"
            fi
          fi
        }

        use_alternative_files "$TARGET"
