name: Use Alternative Files
description: Uses Alternative Files
branding:
  icon: file
  color: blue
inputs:
  target:
    description: Target file or directory
    required: true
    default: .
runs:
  using: composite
  steps:
  
    - shell: bash
      env:
        TARGET: ${{ inputs.target }}
      run: |
        use_alt_files () {
          cd "$1"
          for item in *; do 
            if [[ -d $item ]]; then
              use_alt_files "$item"
            else
              use_alt_file "$item"
            fi
          done
          cd ..
        }

        use_alt_file () {
          item="$1"
          template="${item%.*}.template.${item##*.}"
          if [ -f $template ]; then
            cat $template > $item
            rm $template
          fi
        }

        if [ -d "$TARGET" ]; then
          use_alt_files "$TARGET"
        elif [ -f "$TARGET" ]; then
          use_alt_file "$TARGET"
        else
          echo "Target file not found: $TARGET"
          exit 1
        fi
