name: Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Test Action
        uses: ./
        with:
          target: test

      - name: Check Result
        run: |
          contents=$(ls test)
          if [[ "$contents" != 'test.md' ]]; then
            echo "unexpected directory contents: $contents"
            exit 1
          fi
          expected='# test alt'
          actual=$(cat test/test.md)
          if [[ "$actual" != "$expected" ]]; then
            echo "unexpected result: $actual"
            exit 1
          fi
