name: Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Test Action
        uses: ./
        with:
          target: test

      - name: Check Result
        run: |
          expected='# test alt'
          actual=$(cat test/test.md)
          if [[ "actual" != "$expected" ]]; then
            echo "Unexpected result: $actual"
            exit 1
          fi
